Feat: #62 feat 마이페이지 사이드메뉴 프로필 이미지 - 중간 점검
thatsrightcat/codeit-12 pull request #65
Opened 2024-08-06 02:56 UTC by thatsrightcat

## 관련 이슈 (Related Issues)

Fixes #62 

## 변경 사항 (Changes)

- 모바일 화면 시 사이드 네비게이션이 안보이게 처리하였습니다. 추후에 모바일 햄버거 버튼으로 대체할 예정입니다.
- 프로필 이미지는 로딩중, 이미지 있을 때, 이미지 없을 때 에 맞추어 렌더링하도록 하였습니다.

## 체크리스트 (Checklist)

- [x] 코드가 제대로 동작하는지 테스트함
- [ ] 코드 컨벤션을 잘 지킴

## 추가 설명 (Additional Context)

### 프로필 이미지가 있을 때
<img width="402" alt="image" src="https://github.com/user-attachments/assets/c10cd683-b838-43b1-8d2a-0062a3878211">

### 프로필 이미지가 없을 때
<img width="423" alt="image" src="https://github.com/user-attachments/assets/37f43b37-9d87-4891-a844-80fd2e7ab6b4">

## 리뷰어 참고 사항 (Notes for Reviewers)

- 리액트 쿼리 이렇게쓰는거 맞는지 아직도 감이 잘 안잡힙니다...ㅠㅠ 더 좋은 방법이 있어보인다면 훈수 대환영

2024-08-06 04:53 UTC, greenyun2 approved these changes
커스텀 훅을 사용해서 코드가 일기 좋은거 같습니다

2024-08-07 01:58 UTC, MJY1993 requested changes

2024-08-07 01:58 UTC, MJY1993 commented on middleware.ts
> +
미들웨어 추가하셨네요 !
토큰 없이 /activity-list에 접근해봤는데 콘솔창이 엄청 바빠보입니다 !

2024-08-07 06:24 UTC, MJY1993 approved these changes
미들웨어라는 개념도 꼭 필요했던건데 덕분에 배울 수 있었네요 !! 감사합니다 !!

2024-08-08 05:05 UTC, Park-Jingyeong approved these changes
react query 잘 되셔서 다행이에요!
저는 api 호출 함수랑 useQuery 함수 둘다 한 파일에 묶어버렸는데
소정님은 api 호출 함수는 api 폴더에 하셨네요! 
수고 많으십니다👍👍

2024-08-08 06:44 UTC, baehyunji approved these changes
에러 해결하셨군요! 수고 많으셨습니다

2024-08-08 09:43 UTC, merged